// Generated by gencpp from file rosplan_tiago_scenarios_msgs/GetItemResult.msg
// DO NOT EDIT!


#ifndef ROSPLAN_TIAGO_SCENARIOS_MSGS_MESSAGE_GETITEMRESULT_H
#define ROSPLAN_TIAGO_SCENARIOS_MSGS_MESSAGE_GETITEMRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_tiago_scenarios_msgs
{
template <class ContainerAllocator>
struct GetItemResult_
{
  typedef GetItemResult_<ContainerAllocator> Type;

  GetItemResult_()
    : is_item_acquired(false)  {
    }
  GetItemResult_(const ContainerAllocator& _alloc)
    : is_item_acquired(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_item_acquired_type;
  _is_item_acquired_type is_item_acquired;





  typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> const> ConstPtr;

}; // struct GetItemResult_

typedef ::rosplan_tiago_scenarios_msgs::GetItemResult_<std::allocator<void> > GetItemResult;

typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::GetItemResult > GetItemResultPtr;
typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::GetItemResult const> GetItemResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator1> & lhs, const ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator2> & rhs)
{
  return lhs.is_item_acquired == rhs.is_item_acquired;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator1> & lhs, const ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_tiago_scenarios_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c8e16ad7627acb0691256abe024ddac";
  }

  static const char* value(const ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c8e16ad7627acb0ULL;
  static const uint64_t static_value2 = 0x691256abe024ddacULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_tiago_scenarios_msgs/GetItemResult";
  }

  static const char* value(const ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool is_item_acquired\n"
;
  }

  static const char* value(const ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_item_acquired);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetItemResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_tiago_scenarios_msgs::GetItemResult_<ContainerAllocator>& v)
  {
    s << indent << "is_item_acquired: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_item_acquired);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_TIAGO_SCENARIOS_MSGS_MESSAGE_GETITEMRESULT_H
