// Generated by gencpp from file rosplan_tiago_scenarios_msgs/GreetGoal.msg
// DO NOT EDIT!


#ifndef ROSPLAN_TIAGO_SCENARIOS_MSGS_MESSAGE_GREETGOAL_H
#define ROSPLAN_TIAGO_SCENARIOS_MSGS_MESSAGE_GREETGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_tiago_scenarios_msgs
{
template <class ContainerAllocator>
struct GreetGoal_
{
  typedef GreetGoal_<ContainerAllocator> Type;

  GreetGoal_()
    : greet_scenario()  {
    }
  GreetGoal_(const ContainerAllocator& _alloc)
    : greet_scenario(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _greet_scenario_type;
  _greet_scenario_type greet_scenario;





  typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GreetGoal_

typedef ::rosplan_tiago_scenarios_msgs::GreetGoal_<std::allocator<void> > GreetGoal;

typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::GreetGoal > GreetGoalPtr;
typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::GreetGoal const> GreetGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator1> & lhs, const ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator2> & rhs)
{
  return lhs.greet_scenario == rhs.greet_scenario;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator1> & lhs, const ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_tiago_scenarios_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf68f4c2844e12cf3045b23277a7fec9";
  }

  static const char* value(const ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf68f4c2844e12cfULL;
  static const uint64_t static_value2 = 0x3045b23277a7fec9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_tiago_scenarios_msgs/GreetGoal";
  }

  static const char* value(const ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"string greet_scenario\n"
;
  }

  static const char* value(const ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.greet_scenario);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GreetGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_tiago_scenarios_msgs::GreetGoal_<ContainerAllocator>& v)
  {
    s << indent << "greet_scenario: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.greet_scenario);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_TIAGO_SCENARIOS_MSGS_MESSAGE_GREETGOAL_H
