// Generated by gencpp from file rosplan_tiago_scenarios_msgs/HumanApproachDetectGoal.msg
// DO NOT EDIT!


#ifndef ROSPLAN_TIAGO_SCENARIOS_MSGS_MESSAGE_HUMANAPPROACHDETECTGOAL_H
#define ROSPLAN_TIAGO_SCENARIOS_MSGS_MESSAGE_HUMANAPPROACHDETECTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_tiago_scenarios_msgs
{
template <class ContainerAllocator>
struct HumanApproachDetectGoal_
{
  typedef HumanApproachDetectGoal_<ContainerAllocator> Type;

  HumanApproachDetectGoal_()
    : dummy_goal(0.0)  {
    }
  HumanApproachDetectGoal_(const ContainerAllocator& _alloc)
    : dummy_goal(0.0)  {
  (void)_alloc;
    }



   typedef float _dummy_goal_type;
  _dummy_goal_type dummy_goal;





  typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> const> ConstPtr;

}; // struct HumanApproachDetectGoal_

typedef ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<std::allocator<void> > HumanApproachDetectGoal;

typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal > HumanApproachDetectGoalPtr;
typedef boost::shared_ptr< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal const> HumanApproachDetectGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator1> & lhs, const ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator2> & rhs)
{
  return lhs.dummy_goal == rhs.dummy_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator1> & lhs, const ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_tiago_scenarios_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "528343dee280a1516b28f3a457c32ac3";
  }

  static const char* value(const ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x528343dee280a151ULL;
  static const uint64_t static_value2 = 0x6b28f3a457c32ac3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_tiago_scenarios_msgs/HumanApproachDetectGoal";
  }

  static const char* value(const ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"float32 dummy_goal\n"
;
  }

  static const char* value(const ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dummy_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanApproachDetectGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_tiago_scenarios_msgs::HumanApproachDetectGoal_<ContainerAllocator>& v)
  {
    s << indent << "dummy_goal: ";
    Printer<float>::stream(s, indent + "  ", v.dummy_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_TIAGO_SCENARIOS_MSGS_MESSAGE_HUMANAPPROACHDETECTGOAL_H
