// Generated by gencpp from file pardon_action_server/TurnToHumanResult.msg
// DO NOT EDIT!


#ifndef PARDON_ACTION_SERVER_MESSAGE_TURNTOHUMANRESULT_H
#define PARDON_ACTION_SERVER_MESSAGE_TURNTOHUMANRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace pardon_action_server
{
template <class ContainerAllocator>
struct TurnToHumanResult_
{
  typedef TurnToHumanResult_<ContainerAllocator> Type;

  TurnToHumanResult_()
    : status()  {
    }
  TurnToHumanResult_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> const> ConstPtr;

}; // struct TurnToHumanResult_

typedef ::pardon_action_server::TurnToHumanResult_<std::allocator<void> > TurnToHumanResult;

typedef boost::shared_ptr< ::pardon_action_server::TurnToHumanResult > TurnToHumanResultPtr;
typedef boost::shared_ptr< ::pardon_action_server::TurnToHumanResult const> TurnToHumanResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pardon_action_server::TurnToHumanResult_<ContainerAllocator1> & lhs, const ::pardon_action_server::TurnToHumanResult_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pardon_action_server::TurnToHumanResult_<ContainerAllocator1> & lhs, const ::pardon_action_server::TurnToHumanResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pardon_action_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da740a2c07d1e6cb851fc1b477c8705a";
  }

  static const char* value(const ::pardon_action_server::TurnToHumanResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda740a2c07d1e6cbULL;
  static const uint64_t static_value2 = 0x851fc1b477c8705aULL;
};

template<class ContainerAllocator>
struct DataType< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pardon_action_server/TurnToHumanResult";
  }

  static const char* value(const ::pardon_action_server::TurnToHumanResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"std_msgs/String status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::pardon_action_server::TurnToHumanResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnToHumanResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pardon_action_server::TurnToHumanResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pardon_action_server::TurnToHumanResult_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PARDON_ACTION_SERVER_MESSAGE_TURNTOHUMANRESULT_H
