(cl:defpackage tiago_msgs-msg
  (:use )
  (:export
   "<CASEINSTANCE>"
   "CASEINSTANCE"
   "<COMMAND>"
   "COMMAND"
   "<DYNAGENTDIAG>"
   "DYNAGENTDIAG"
   "<HAZARDOBJECT>"
   "HAZARDOBJECT"
   "<SAYSENTENCEACTION>"
   "SAYSENTENCEACTION"
   "<SAYSENTENCEACTIONFEEDBACK>"
   "SAYSENTENCEACTIONFEEDBACK"
   "<SAYSENTENCEACTIONGOAL>"
   "SAYSENTENCEACTIONGOAL"
   "<SAYSENTENCEACTIONRESULT>"
   "SAYSENTENCEACTIONRESULT"
   "<SAYSENTENCEFEEDBACK>"
   "SAYSENTENCEFEEDBACK"
   "<SAYSENTENCEGOAL>"
   "SAYSENTENCEGOAL"
   "<SAYSENTENCERESULT>"
   "SAYSENTENCERESULT"
  ))

