; Auto-generated. Do not edit!


(cl:in-package tiago_msgs-msg)


;//! \htmlinclude SaySentenceGoal.msg.html

(cl:defclass <SaySentenceGoal> (roslisp-msg-protocol:ros-message)
  ((sentence
    :reader sentence
    :initarg :sentence
    :type cl:string
    :initform ""))
)

(cl:defclass SaySentenceGoal (<SaySentenceGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SaySentenceGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SaySentenceGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tiago_msgs-msg:<SaySentenceGoal> is deprecated: use tiago_msgs-msg:SaySentenceGoal instead.")))

(cl:ensure-generic-function 'sentence-val :lambda-list '(m))
(cl:defmethod sentence-val ((m <SaySentenceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago_msgs-msg:sentence-val is deprecated.  Use tiago_msgs-msg:sentence instead.")
  (sentence m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SaySentenceGoal>) ostream)
  "Serializes a message object of type '<SaySentenceGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'sentence))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'sentence))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SaySentenceGoal>) istream)
  "Deserializes a message object of type '<SaySentenceGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'sentence) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'sentence) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SaySentenceGoal>)))
  "Returns string type for a message object of type '<SaySentenceGoal>"
  "tiago_msgs/SaySentenceGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SaySentenceGoal)))
  "Returns string type for a message object of type 'SaySentenceGoal"
  "tiago_msgs/SaySentenceGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SaySentenceGoal>)))
  "Returns md5sum for a message object of type '<SaySentenceGoal>"
  "3ee8e7a1b3ec1e5b34263db750df6246")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SaySentenceGoal)))
  "Returns md5sum for a message object of type 'SaySentenceGoal"
  "3ee8e7a1b3ec1e5b34263db750df6246")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SaySentenceGoal>)))
  "Returns full string definition for message of type '<SaySentenceGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string sentence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SaySentenceGoal)))
  "Returns full string definition for message of type 'SaySentenceGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string sentence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SaySentenceGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'sentence))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SaySentenceGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SaySentenceGoal
    (cl:cons ':sentence (sentence msg))
))
