(cl:defpackage rosplan_tiago_core_msgs-srv
  (:use )
  (:export
   "GETHUMAN"
   "<GETHUMAN-REQUEST>"
   "GETHUMAN-REQUEST"
   "<GETHUMAN-RESPONSE>"
   "GETHUMAN-RESPONSE"
   "GETLOCATION"
   "<GETLOCATION-REQUEST>"
   "GETLOCATION-REQUEST"
   "<GETLOCATION-RESPONSE>"
   "GETLOCATION-RESPONSE"
  ))

