; Auto-generated. Do not edit!


(cl:in-package pardon_action_server-msg)


;//! \htmlinclude TurnToHumanResult.msg.html

(cl:defclass <TurnToHumanResult> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass TurnToHumanResult (<TurnToHumanResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurnToHumanResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurnToHumanResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pardon_action_server-msg:<TurnToHumanResult> is deprecated: use pardon_action_server-msg:TurnToHumanResult instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <TurnToHumanResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pardon_action_server-msg:status-val is deprecated.  Use pardon_action_server-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurnToHumanResult>) ostream)
  "Serializes a message object of type '<TurnToHumanResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'status) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurnToHumanResult>) istream)
  "Deserializes a message object of type '<TurnToHumanResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'status) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurnToHumanResult>)))
  "Returns string type for a message object of type '<TurnToHumanResult>"
  "pardon_action_server/TurnToHumanResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurnToHumanResult)))
  "Returns string type for a message object of type 'TurnToHumanResult"
  "pardon_action_server/TurnToHumanResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurnToHumanResult>)))
  "Returns md5sum for a message object of type '<TurnToHumanResult>"
  "da740a2c07d1e6cb851fc1b477c8705a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurnToHumanResult)))
  "Returns md5sum for a message object of type 'TurnToHumanResult"
  "da740a2c07d1e6cb851fc1b477c8705a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurnToHumanResult>)))
  "Returns full string definition for message of type '<TurnToHumanResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/String status~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurnToHumanResult)))
  "Returns full string definition for message of type 'TurnToHumanResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/String status~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurnToHumanResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurnToHumanResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TurnToHumanResult
    (cl:cons ':status (status msg))
))
