; Auto-generated. Do not edit!


(cl:in-package pardon_action_server-msg)


;//! \htmlinclude TurnToHumanFeedback.msg.html

(cl:defclass <TurnToHumanFeedback> (roslisp-msg-protocol:ros-message)
  ((orientation
    :reader orientation
    :initarg :orientation
    :type geometry_msgs-msg:Quaternion
    :initform (cl:make-instance 'geometry_msgs-msg:Quaternion))
   (status
    :reader status
    :initarg :status
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass TurnToHumanFeedback (<TurnToHumanFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurnToHumanFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurnToHumanFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pardon_action_server-msg:<TurnToHumanFeedback> is deprecated: use pardon_action_server-msg:TurnToHumanFeedback instead.")))

(cl:ensure-generic-function 'orientation-val :lambda-list '(m))
(cl:defmethod orientation-val ((m <TurnToHumanFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pardon_action_server-msg:orientation-val is deprecated.  Use pardon_action_server-msg:orientation instead.")
  (orientation m))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <TurnToHumanFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pardon_action_server-msg:status-val is deprecated.  Use pardon_action_server-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurnToHumanFeedback>) ostream)
  "Serializes a message object of type '<TurnToHumanFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'orientation) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'status) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurnToHumanFeedback>) istream)
  "Deserializes a message object of type '<TurnToHumanFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'orientation) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'status) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurnToHumanFeedback>)))
  "Returns string type for a message object of type '<TurnToHumanFeedback>"
  "pardon_action_server/TurnToHumanFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurnToHumanFeedback)))
  "Returns string type for a message object of type 'TurnToHumanFeedback"
  "pardon_action_server/TurnToHumanFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurnToHumanFeedback>)))
  "Returns md5sum for a message object of type '<TurnToHumanFeedback>"
  "5adcad5c6c073483cbd46dd8aca29213")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurnToHumanFeedback)))
  "Returns md5sum for a message object of type 'TurnToHumanFeedback"
  "5adcad5c6c073483cbd46dd8aca29213")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurnToHumanFeedback>)))
  "Returns full string definition for message of type '<TurnToHumanFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Quaternion orientation~%std_msgs/String status~%~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurnToHumanFeedback)))
  "Returns full string definition for message of type 'TurnToHumanFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Quaternion orientation~%std_msgs/String status~%~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurnToHumanFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'orientation))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurnToHumanFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TurnToHumanFeedback
    (cl:cons ':orientation (orientation msg))
    (cl:cons ':status (status msg))
))
