; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude CheckDoorResult.msg.html

(cl:defclass <CheckDoorResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CheckDoorResult (<CheckDoorResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CheckDoorResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CheckDoorResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<CheckDoorResult> is deprecated: use rosplan_tiago_scenarios_msgs-msg:CheckDoorResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CheckDoorResult>) ostream)
  "Serializes a message object of type '<CheckDoorResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CheckDoorResult>) istream)
  "Deserializes a message object of type '<CheckDoorResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CheckDoorResult>)))
  "Returns string type for a message object of type '<CheckDoorResult>"
  "rosplan_tiago_scenarios_msgs/CheckDoorResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CheckDoorResult)))
  "Returns string type for a message object of type 'CheckDoorResult"
  "rosplan_tiago_scenarios_msgs/CheckDoorResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CheckDoorResult>)))
  "Returns md5sum for a message object of type '<CheckDoorResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CheckDoorResult)))
  "Returns md5sum for a message object of type 'CheckDoorResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CheckDoorResult>)))
  "Returns full string definition for message of type '<CheckDoorResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CheckDoorResult)))
  "Returns full string definition for message of type 'CheckDoorResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CheckDoorResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CheckDoorResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CheckDoorResult
))
