; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude CheckDoorGoal.msg.html

(cl:defclass <CheckDoorGoal> (roslisp-msg-protocol:ros-message)
  ((sensor
    :reader sensor
    :initarg :sensor
    :type cl:string
    :initform ""))
)

(cl:defclass CheckDoorGoal (<CheckDoorGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CheckDoorGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CheckDoorGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<CheckDoorGoal> is deprecated: use rosplan_tiago_scenarios_msgs-msg:CheckDoorGoal instead.")))

(cl:ensure-generic-function 'sensor-val :lambda-list '(m))
(cl:defmethod sensor-val ((m <CheckDoorGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:sensor-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:sensor instead.")
  (sensor m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CheckDoorGoal>) ostream)
  "Serializes a message object of type '<CheckDoorGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'sensor))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'sensor))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CheckDoorGoal>) istream)
  "Deserializes a message object of type '<CheckDoorGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'sensor) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'sensor) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CheckDoorGoal>)))
  "Returns string type for a message object of type '<CheckDoorGoal>"
  "rosplan_tiago_scenarios_msgs/CheckDoorGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CheckDoorGoal)))
  "Returns string type for a message object of type 'CheckDoorGoal"
  "rosplan_tiago_scenarios_msgs/CheckDoorGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CheckDoorGoal>)))
  "Returns md5sum for a message object of type '<CheckDoorGoal>"
  "c6599601f6241c1bc9e4676bbeb31d89")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CheckDoorGoal)))
  "Returns md5sum for a message object of type 'CheckDoorGoal"
  "c6599601f6241c1bc9e4676bbeb31d89")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CheckDoorGoal>)))
  "Returns full string definition for message of type '<CheckDoorGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string sensor~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CheckDoorGoal)))
  "Returns full string definition for message of type 'CheckDoorGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string sensor~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CheckDoorGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'sensor))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CheckDoorGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CheckDoorGoal
    (cl:cons ':sensor (sensor msg))
))
