; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude CheckLightGoal.msg.html

(cl:defclass <CheckLightGoal> (roslisp-msg-protocol:ros-message)
  ((sensor
    :reader sensor
    :initarg :sensor
    :type cl:string
    :initform ""))
)

(cl:defclass CheckLightGoal (<CheckLightGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CheckLightGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CheckLightGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<CheckLightGoal> is deprecated: use rosplan_tiago_scenarios_msgs-msg:CheckLightGoal instead.")))

(cl:ensure-generic-function 'sensor-val :lambda-list '(m))
(cl:defmethod sensor-val ((m <CheckLightGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:sensor-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:sensor instead.")
  (sensor m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CheckLightGoal>) ostream)
  "Serializes a message object of type '<CheckLightGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'sensor))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'sensor))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CheckLightGoal>) istream)
  "Deserializes a message object of type '<CheckLightGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'sensor) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'sensor) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CheckLightGoal>)))
  "Returns string type for a message object of type '<CheckLightGoal>"
  "rosplan_tiago_scenarios_msgs/CheckLightGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CheckLightGoal)))
  "Returns string type for a message object of type 'CheckLightGoal"
  "rosplan_tiago_scenarios_msgs/CheckLightGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CheckLightGoal>)))
  "Returns md5sum for a message object of type '<CheckLightGoal>"
  "c6599601f6241c1bc9e4676bbeb31d89")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CheckLightGoal)))
  "Returns md5sum for a message object of type 'CheckLightGoal"
  "c6599601f6241c1bc9e4676bbeb31d89")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CheckLightGoal>)))
  "Returns full string definition for message of type '<CheckLightGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string sensor~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CheckLightGoal)))
  "Returns full string definition for message of type 'CheckLightGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string sensor~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CheckLightGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'sensor))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CheckLightGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CheckLightGoal
    (cl:cons ':sensor (sensor msg))
))
