; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude GetItemGoal.msg.html

(cl:defclass <GetItemGoal> (roslisp-msg-protocol:ros-message)
  ((item
    :reader item
    :initarg :item
    :type cl:string
    :initform ""))
)

(cl:defclass GetItemGoal (<GetItemGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetItemGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetItemGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<GetItemGoal> is deprecated: use rosplan_tiago_scenarios_msgs-msg:GetItemGoal instead.")))

(cl:ensure-generic-function 'item-val :lambda-list '(m))
(cl:defmethod item-val ((m <GetItemGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:item-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:item instead.")
  (item m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetItemGoal>) ostream)
  "Serializes a message object of type '<GetItemGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'item))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'item))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetItemGoal>) istream)
  "Deserializes a message object of type '<GetItemGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'item) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'item) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetItemGoal>)))
  "Returns string type for a message object of type '<GetItemGoal>"
  "rosplan_tiago_scenarios_msgs/GetItemGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetItemGoal)))
  "Returns string type for a message object of type 'GetItemGoal"
  "rosplan_tiago_scenarios_msgs/GetItemGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetItemGoal>)))
  "Returns md5sum for a message object of type '<GetItemGoal>"
  "2d14a38979abbdbe6981f6dc67e36fef")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetItemGoal)))
  "Returns md5sum for a message object of type 'GetItemGoal"
  "2d14a38979abbdbe6981f6dc67e36fef")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetItemGoal>)))
  "Returns full string definition for message of type '<GetItemGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string item~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetItemGoal)))
  "Returns full string definition for message of type 'GetItemGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string item~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetItemGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'item))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetItemGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GetItemGoal
    (cl:cons ':item (item msg))
))
