; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude GetItemResult.msg.html

(cl:defclass <GetItemResult> (roslisp-msg-protocol:ros-message)
  ((is_item_acquired
    :reader is_item_acquired
    :initarg :is_item_acquired
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GetItemResult (<GetItemResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetItemResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetItemResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<GetItemResult> is deprecated: use rosplan_tiago_scenarios_msgs-msg:GetItemResult instead.")))

(cl:ensure-generic-function 'is_item_acquired-val :lambda-list '(m))
(cl:defmethod is_item_acquired-val ((m <GetItemResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:is_item_acquired-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:is_item_acquired instead.")
  (is_item_acquired m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetItemResult>) ostream)
  "Serializes a message object of type '<GetItemResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_item_acquired) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetItemResult>) istream)
  "Deserializes a message object of type '<GetItemResult>"
    (cl:setf (cl:slot-value msg 'is_item_acquired) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetItemResult>)))
  "Returns string type for a message object of type '<GetItemResult>"
  "rosplan_tiago_scenarios_msgs/GetItemResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetItemResult)))
  "Returns string type for a message object of type 'GetItemResult"
  "rosplan_tiago_scenarios_msgs/GetItemResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetItemResult>)))
  "Returns md5sum for a message object of type '<GetItemResult>"
  "0c8e16ad7627acb0691256abe024ddac")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetItemResult)))
  "Returns md5sum for a message object of type 'GetItemResult"
  "0c8e16ad7627acb0691256abe024ddac")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetItemResult>)))
  "Returns full string definition for message of type '<GetItemResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool is_item_acquired~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetItemResult)))
  "Returns full string definition for message of type 'GetItemResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool is_item_acquired~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetItemResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetItemResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GetItemResult
    (cl:cons ':is_item_acquired (is_item_acquired msg))
))
