; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude GetLoadGoal.msg.html

(cl:defclass <GetLoadGoal> (roslisp-msg-protocol:ros-message)
  ((human
    :reader human
    :initarg :human
    :type people_msgs-msg:Person
    :initform (cl:make-instance 'people_msgs-msg:Person)))
)

(cl:defclass GetLoadGoal (<GetLoadGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetLoadGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetLoadGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<GetLoadGoal> is deprecated: use rosplan_tiago_scenarios_msgs-msg:GetLoadGoal instead.")))

(cl:ensure-generic-function 'human-val :lambda-list '(m))
(cl:defmethod human-val ((m <GetLoadGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:human-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:human instead.")
  (human m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetLoadGoal>) ostream)
  "Serializes a message object of type '<GetLoadGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'human) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetLoadGoal>) istream)
  "Deserializes a message object of type '<GetLoadGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'human) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetLoadGoal>)))
  "Returns string type for a message object of type '<GetLoadGoal>"
  "rosplan_tiago_scenarios_msgs/GetLoadGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetLoadGoal)))
  "Returns string type for a message object of type 'GetLoadGoal"
  "rosplan_tiago_scenarios_msgs/GetLoadGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetLoadGoal>)))
  "Returns md5sum for a message object of type '<GetLoadGoal>"
  "abe471379b81e0341b94c19d1a0e7c0c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetLoadGoal)))
  "Returns md5sum for a message object of type 'GetLoadGoal"
  "abe471379b81e0341b94c19d1a0e7c0c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetLoadGoal>)))
  "Returns full string definition for message of type '<GetLoadGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%people_msgs/Person human~%~%================================================================================~%MSG: people_msgs/Person~%string              name~%geometry_msgs/Point position~%geometry_msgs/Point velocity~%float64             reliability~%string[]            tagnames~%string[]            tags~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetLoadGoal)))
  "Returns full string definition for message of type 'GetLoadGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%people_msgs/Person human~%~%================================================================================~%MSG: people_msgs/Person~%string              name~%geometry_msgs/Point position~%geometry_msgs/Point velocity~%float64             reliability~%string[]            tagnames~%string[]            tags~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetLoadGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'human))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetLoadGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GetLoadGoal
    (cl:cons ':human (human msg))
))
