; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude GetLoadFeedback.msg.html

(cl:defclass <GetLoadFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GetLoadFeedback (<GetLoadFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetLoadFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetLoadFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<GetLoadFeedback> is deprecated: use rosplan_tiago_scenarios_msgs-msg:GetLoadFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetLoadFeedback>) ostream)
  "Serializes a message object of type '<GetLoadFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetLoadFeedback>) istream)
  "Deserializes a message object of type '<GetLoadFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetLoadFeedback>)))
  "Returns string type for a message object of type '<GetLoadFeedback>"
  "rosplan_tiago_scenarios_msgs/GetLoadFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetLoadFeedback)))
  "Returns string type for a message object of type 'GetLoadFeedback"
  "rosplan_tiago_scenarios_msgs/GetLoadFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetLoadFeedback>)))
  "Returns md5sum for a message object of type '<GetLoadFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetLoadFeedback)))
  "Returns md5sum for a message object of type 'GetLoadFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetLoadFeedback>)))
  "Returns full string definition for message of type '<GetLoadFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetLoadFeedback)))
  "Returns full string definition for message of type 'GetLoadFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetLoadFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetLoadFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GetLoadFeedback
))
