; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude GiveItemFeedback.msg.html

(cl:defclass <GiveItemFeedback> (roslisp-msg-protocol:ros-message)
  ((time_left
    :reader time_left
    :initarg :time_left
    :type cl:fixnum
    :initform 0)
   (is_item_detected
    :reader is_item_detected
    :initarg :is_item_detected
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GiveItemFeedback (<GiveItemFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GiveItemFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GiveItemFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<GiveItemFeedback> is deprecated: use rosplan_tiago_scenarios_msgs-msg:GiveItemFeedback instead.")))

(cl:ensure-generic-function 'time_left-val :lambda-list '(m))
(cl:defmethod time_left-val ((m <GiveItemFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:time_left-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:time_left instead.")
  (time_left m))

(cl:ensure-generic-function 'is_item_detected-val :lambda-list '(m))
(cl:defmethod is_item_detected-val ((m <GiveItemFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:is_item_detected-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:is_item_detected instead.")
  (is_item_detected m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GiveItemFeedback>) ostream)
  "Serializes a message object of type '<GiveItemFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'time_left)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_item_detected) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GiveItemFeedback>) istream)
  "Deserializes a message object of type '<GiveItemFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'time_left) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
    (cl:setf (cl:slot-value msg 'is_item_detected) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GiveItemFeedback>)))
  "Returns string type for a message object of type '<GiveItemFeedback>"
  "rosplan_tiago_scenarios_msgs/GiveItemFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GiveItemFeedback)))
  "Returns string type for a message object of type 'GiveItemFeedback"
  "rosplan_tiago_scenarios_msgs/GiveItemFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GiveItemFeedback>)))
  "Returns md5sum for a message object of type '<GiveItemFeedback>"
  "f9bbf0397c36b53dd120d617b82d90da")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GiveItemFeedback)))
  "Returns md5sum for a message object of type 'GiveItemFeedback"
  "f9bbf0397c36b53dd120d617b82d90da")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GiveItemFeedback>)))
  "Returns full string definition for message of type '<GiveItemFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Message~%int16 time_left~%bool is_item_detected~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GiveItemFeedback)))
  "Returns full string definition for message of type 'GiveItemFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Message~%int16 time_left~%bool is_item_detected~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GiveItemFeedback>))
  (cl:+ 0
     2
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GiveItemFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GiveItemFeedback
    (cl:cons ':time_left (time_left msg))
    (cl:cons ':is_item_detected (is_item_detected msg))
))
