; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude GoResult.msg.html

(cl:defclass <GoResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GoResult (<GoResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<GoResult> is deprecated: use rosplan_tiago_scenarios_msgs-msg:GoResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoResult>) ostream)
  "Serializes a message object of type '<GoResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoResult>) istream)
  "Deserializes a message object of type '<GoResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoResult>)))
  "Returns string type for a message object of type '<GoResult>"
  "rosplan_tiago_scenarios_msgs/GoResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoResult)))
  "Returns string type for a message object of type 'GoResult"
  "rosplan_tiago_scenarios_msgs/GoResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoResult>)))
  "Returns md5sum for a message object of type '<GoResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoResult)))
  "Returns md5sum for a message object of type 'GoResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoResult>)))
  "Returns full string definition for message of type '<GoResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%# bool is_goal_accomplished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoResult)))
  "Returns full string definition for message of type 'GoResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%# bool is_goal_accomplished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GoResult
))
