; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude GoScanningResult.msg.html

(cl:defclass <GoScanningResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GoScanningResult (<GoScanningResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoScanningResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoScanningResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<GoScanningResult> is deprecated: use rosplan_tiago_scenarios_msgs-msg:GoScanningResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoScanningResult>) ostream)
  "Serializes a message object of type '<GoScanningResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoScanningResult>) istream)
  "Deserializes a message object of type '<GoScanningResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoScanningResult>)))
  "Returns string type for a message object of type '<GoScanningResult>"
  "rosplan_tiago_scenarios_msgs/GoScanningResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoScanningResult)))
  "Returns string type for a message object of type 'GoScanningResult"
  "rosplan_tiago_scenarios_msgs/GoScanningResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoScanningResult>)))
  "Returns md5sum for a message object of type '<GoScanningResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoScanningResult)))
  "Returns md5sum for a message object of type 'GoScanningResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoScanningResult>)))
  "Returns full string definition for message of type '<GoScanningResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%# bool is_goal_accomplished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoScanningResult)))
  "Returns full string definition for message of type 'GoScanningResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%# bool is_goal_accomplished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoScanningResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoScanningResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GoScanningResult
))
