; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude GoWithAttendanceFeedback.msg.html

(cl:defclass <GoWithAttendanceFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GoWithAttendanceFeedback (<GoWithAttendanceFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoWithAttendanceFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoWithAttendanceFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<GoWithAttendanceFeedback> is deprecated: use rosplan_tiago_scenarios_msgs-msg:GoWithAttendanceFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoWithAttendanceFeedback>) ostream)
  "Serializes a message object of type '<GoWithAttendanceFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoWithAttendanceFeedback>) istream)
  "Deserializes a message object of type '<GoWithAttendanceFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoWithAttendanceFeedback>)))
  "Returns string type for a message object of type '<GoWithAttendanceFeedback>"
  "rosplan_tiago_scenarios_msgs/GoWithAttendanceFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoWithAttendanceFeedback)))
  "Returns string type for a message object of type 'GoWithAttendanceFeedback"
  "rosplan_tiago_scenarios_msgs/GoWithAttendanceFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoWithAttendanceFeedback>)))
  "Returns md5sum for a message object of type '<GoWithAttendanceFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoWithAttendanceFeedback)))
  "Returns md5sum for a message object of type 'GoWithAttendanceFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoWithAttendanceFeedback>)))
  "Returns full string definition for message of type '<GoWithAttendanceFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoWithAttendanceFeedback)))
  "Returns full string definition for message of type 'GoWithAttendanceFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoWithAttendanceFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoWithAttendanceFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GoWithAttendanceFeedback
))
