; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude GoWithAttendanceGoal.msg.html

(cl:defclass <GoWithAttendanceGoal> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose))
   (human
    :reader human
    :initarg :human
    :type people_msgs-msg:Person
    :initform (cl:make-instance 'people_msgs-msg:Person)))
)

(cl:defclass GoWithAttendanceGoal (<GoWithAttendanceGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoWithAttendanceGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoWithAttendanceGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<GoWithAttendanceGoal> is deprecated: use rosplan_tiago_scenarios_msgs-msg:GoWithAttendanceGoal instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <GoWithAttendanceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:pose-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:pose instead.")
  (pose m))

(cl:ensure-generic-function 'human-val :lambda-list '(m))
(cl:defmethod human-val ((m <GoWithAttendanceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:human-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:human instead.")
  (human m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoWithAttendanceGoal>) ostream)
  "Serializes a message object of type '<GoWithAttendanceGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pose) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'human) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoWithAttendanceGoal>) istream)
  "Deserializes a message object of type '<GoWithAttendanceGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pose) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'human) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoWithAttendanceGoal>)))
  "Returns string type for a message object of type '<GoWithAttendanceGoal>"
  "rosplan_tiago_scenarios_msgs/GoWithAttendanceGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoWithAttendanceGoal)))
  "Returns string type for a message object of type 'GoWithAttendanceGoal"
  "rosplan_tiago_scenarios_msgs/GoWithAttendanceGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoWithAttendanceGoal>)))
  "Returns md5sum for a message object of type '<GoWithAttendanceGoal>"
  "603ea39f51feb72b00e9f4df1b552956")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoWithAttendanceGoal)))
  "Returns md5sum for a message object of type 'GoWithAttendanceGoal"
  "603ea39f51feb72b00e9f4df1b552956")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoWithAttendanceGoal>)))
  "Returns full string definition for message of type '<GoWithAttendanceGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%geometry_msgs/Pose pose~%people_msgs/Person human~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: people_msgs/Person~%string              name~%geometry_msgs/Point position~%geometry_msgs/Point velocity~%float64             reliability~%string[]            tagnames~%string[]            tags~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoWithAttendanceGoal)))
  "Returns full string definition for message of type 'GoWithAttendanceGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%geometry_msgs/Pose pose~%people_msgs/Person human~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: people_msgs/Person~%string              name~%geometry_msgs/Point position~%geometry_msgs/Point velocity~%float64             reliability~%string[]            tagnames~%string[]            tags~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoWithAttendanceGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pose))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'human))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoWithAttendanceGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GoWithAttendanceGoal
    (cl:cons ':pose (pose msg))
    (cl:cons ':human (human msg))
))
