; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude HumanApproachDetectResult.msg.html

(cl:defclass <HumanApproachDetectResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass HumanApproachDetectResult (<HumanApproachDetectResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HumanApproachDetectResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HumanApproachDetectResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<HumanApproachDetectResult> is deprecated: use rosplan_tiago_scenarios_msgs-msg:HumanApproachDetectResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HumanApproachDetectResult>) ostream)
  "Serializes a message object of type '<HumanApproachDetectResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HumanApproachDetectResult>) istream)
  "Deserializes a message object of type '<HumanApproachDetectResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HumanApproachDetectResult>)))
  "Returns string type for a message object of type '<HumanApproachDetectResult>"
  "rosplan_tiago_scenarios_msgs/HumanApproachDetectResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HumanApproachDetectResult)))
  "Returns string type for a message object of type 'HumanApproachDetectResult"
  "rosplan_tiago_scenarios_msgs/HumanApproachDetectResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HumanApproachDetectResult>)))
  "Returns md5sum for a message object of type '<HumanApproachDetectResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HumanApproachDetectResult)))
  "Returns md5sum for a message object of type 'HumanApproachDetectResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HumanApproachDetectResult>)))
  "Returns full string definition for message of type '<HumanApproachDetectResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%# float32 dummy_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HumanApproachDetectResult)))
  "Returns full string definition for message of type 'HumanApproachDetectResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%# float32 dummy_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HumanApproachDetectResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HumanApproachDetectResult>))
  "Converts a ROS message object to a list"
  (cl:list 'HumanApproachDetectResult
))
