; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude HumanApproachDetectFeedback.msg.html

(cl:defclass <HumanApproachDetectFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass HumanApproachDetectFeedback (<HumanApproachDetectFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HumanApproachDetectFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HumanApproachDetectFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<HumanApproachDetectFeedback> is deprecated: use rosplan_tiago_scenarios_msgs-msg:HumanApproachDetectFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HumanApproachDetectFeedback>) ostream)
  "Serializes a message object of type '<HumanApproachDetectFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HumanApproachDetectFeedback>) istream)
  "Deserializes a message object of type '<HumanApproachDetectFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HumanApproachDetectFeedback>)))
  "Returns string type for a message object of type '<HumanApproachDetectFeedback>"
  "rosplan_tiago_scenarios_msgs/HumanApproachDetectFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HumanApproachDetectFeedback)))
  "Returns string type for a message object of type 'HumanApproachDetectFeedback"
  "rosplan_tiago_scenarios_msgs/HumanApproachDetectFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HumanApproachDetectFeedback>)))
  "Returns md5sum for a message object of type '<HumanApproachDetectFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HumanApproachDetectFeedback)))
  "Returns md5sum for a message object of type 'HumanApproachDetectFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HumanApproachDetectFeedback>)))
  "Returns full string definition for message of type '<HumanApproachDetectFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HumanApproachDetectFeedback)))
  "Returns full string definition for message of type 'HumanApproachDetectFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HumanApproachDetectFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HumanApproachDetectFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'HumanApproachDetectFeedback
))
