; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude HumanInteractFeedback.msg.html

(cl:defclass <HumanInteractFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass HumanInteractFeedback (<HumanInteractFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HumanInteractFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HumanInteractFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<HumanInteractFeedback> is deprecated: use rosplan_tiago_scenarios_msgs-msg:HumanInteractFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HumanInteractFeedback>) ostream)
  "Serializes a message object of type '<HumanInteractFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HumanInteractFeedback>) istream)
  "Deserializes a message object of type '<HumanInteractFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HumanInteractFeedback>)))
  "Returns string type for a message object of type '<HumanInteractFeedback>"
  "rosplan_tiago_scenarios_msgs/HumanInteractFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HumanInteractFeedback)))
  "Returns string type for a message object of type 'HumanInteractFeedback"
  "rosplan_tiago_scenarios_msgs/HumanInteractFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HumanInteractFeedback>)))
  "Returns md5sum for a message object of type '<HumanInteractFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HumanInteractFeedback)))
  "Returns md5sum for a message object of type 'HumanInteractFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HumanInteractFeedback>)))
  "Returns full string definition for message of type '<HumanInteractFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%# float32 percent_of_knowledge_given~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HumanInteractFeedback)))
  "Returns full string definition for message of type 'HumanInteractFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%# float32 percent_of_knowledge_given~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HumanInteractFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HumanInteractFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'HumanInteractFeedback
))
