; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude HumanApproachDetectGoal.msg.html

(cl:defclass <HumanApproachDetectGoal> (roslisp-msg-protocol:ros-message)
  ((dummy_goal
    :reader dummy_goal
    :initarg :dummy_goal
    :type cl:float
    :initform 0.0))
)

(cl:defclass HumanApproachDetectGoal (<HumanApproachDetectGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HumanApproachDetectGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HumanApproachDetectGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<HumanApproachDetectGoal> is deprecated: use rosplan_tiago_scenarios_msgs-msg:HumanApproachDetectGoal instead.")))

(cl:ensure-generic-function 'dummy_goal-val :lambda-list '(m))
(cl:defmethod dummy_goal-val ((m <HumanApproachDetectGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:dummy_goal-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:dummy_goal instead.")
  (dummy_goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HumanApproachDetectGoal>) ostream)
  "Serializes a message object of type '<HumanApproachDetectGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'dummy_goal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HumanApproachDetectGoal>) istream)
  "Deserializes a message object of type '<HumanApproachDetectGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'dummy_goal) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HumanApproachDetectGoal>)))
  "Returns string type for a message object of type '<HumanApproachDetectGoal>"
  "rosplan_tiago_scenarios_msgs/HumanApproachDetectGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HumanApproachDetectGoal)))
  "Returns string type for a message object of type 'HumanApproachDetectGoal"
  "rosplan_tiago_scenarios_msgs/HumanApproachDetectGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HumanApproachDetectGoal>)))
  "Returns md5sum for a message object of type '<HumanApproachDetectGoal>"
  "528343dee280a1516b28f3a457c32ac3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HumanApproachDetectGoal)))
  "Returns md5sum for a message object of type 'HumanApproachDetectGoal"
  "528343dee280a1516b28f3a457c32ac3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HumanApproachDetectGoal>)))
  "Returns full string definition for message of type '<HumanApproachDetectGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float32 dummy_goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HumanApproachDetectGoal)))
  "Returns full string definition for message of type 'HumanApproachDetectGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float32 dummy_goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HumanApproachDetectGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HumanApproachDetectGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'HumanApproachDetectGoal
    (cl:cons ':dummy_goal (dummy_goal msg))
))
