; Auto-generated. Do not edit!


(cl:in-package rosplan_tiago_scenarios_msgs-msg)


;//! \htmlinclude LeaveLoadGoal.msg.html

(cl:defclass <LeaveLoadGoal> (roslisp-msg-protocol:ros-message)
  ((human
    :reader human
    :initarg :human
    :type people_msgs-msg:Person
    :initform (cl:make-instance 'people_msgs-msg:Person)))
)

(cl:defclass LeaveLoadGoal (<LeaveLoadGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LeaveLoadGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LeaveLoadGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rosplan_tiago_scenarios_msgs-msg:<LeaveLoadGoal> is deprecated: use rosplan_tiago_scenarios_msgs-msg:LeaveLoadGoal instead.")))

(cl:ensure-generic-function 'human-val :lambda-list '(m))
(cl:defmethod human-val ((m <LeaveLoadGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rosplan_tiago_scenarios_msgs-msg:human-val is deprecated.  Use rosplan_tiago_scenarios_msgs-msg:human instead.")
  (human m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LeaveLoadGoal>) ostream)
  "Serializes a message object of type '<LeaveLoadGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'human) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LeaveLoadGoal>) istream)
  "Deserializes a message object of type '<LeaveLoadGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'human) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LeaveLoadGoal>)))
  "Returns string type for a message object of type '<LeaveLoadGoal>"
  "rosplan_tiago_scenarios_msgs/LeaveLoadGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LeaveLoadGoal)))
  "Returns string type for a message object of type 'LeaveLoadGoal"
  "rosplan_tiago_scenarios_msgs/LeaveLoadGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LeaveLoadGoal>)))
  "Returns md5sum for a message object of type '<LeaveLoadGoal>"
  "abe471379b81e0341b94c19d1a0e7c0c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LeaveLoadGoal)))
  "Returns md5sum for a message object of type 'LeaveLoadGoal"
  "abe471379b81e0341b94c19d1a0e7c0c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LeaveLoadGoal>)))
  "Returns full string definition for message of type '<LeaveLoadGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%people_msgs/Person human~%~%================================================================================~%MSG: people_msgs/Person~%string              name~%geometry_msgs/Point position~%geometry_msgs/Point velocity~%float64             reliability~%string[]            tagnames~%string[]            tags~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LeaveLoadGoal)))
  "Returns full string definition for message of type 'LeaveLoadGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%people_msgs/Person human~%~%================================================================================~%MSG: people_msgs/Person~%string              name~%geometry_msgs/Point position~%geometry_msgs/Point velocity~%float64             reliability~%string[]            tagnames~%string[]            tags~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LeaveLoadGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'human))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LeaveLoadGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LeaveLoadGoal
    (cl:cons ':human (human msg))
))
