(cl:defpackage tiago_msgs-srv
  (:use )
  (:export
   "DICTIONARYQUERY"
   "<DICTIONARYQUERY-REQUEST>"
   "DICTIONARYQUERY-REQUEST"
   "<DICTIONARYQUERY-RESPONSE>"
   "DICTIONARYQUERY-RESPONSE"
  ))

