// Generated by gencpp from file rosplan_tiago_core_msgs/GetHumanRequest.msg
// DO NOT EDIT!


#ifndef ROSPLAN_TIAGO_CORE_MSGS_MESSAGE_GETHUMANREQUEST_H
#define ROSPLAN_TIAGO_CORE_MSGS_MESSAGE_GETHUMANREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_tiago_core_msgs
{
template <class ContainerAllocator>
struct GetHumanRequest_
{
  typedef GetHumanRequest_<ContainerAllocator> Type;

  GetHumanRequest_()
    : human_name()  {
    }
  GetHumanRequest_(const ContainerAllocator& _alloc)
    : human_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _human_name_type;
  _human_name_type human_name;





  typedef boost::shared_ptr< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetHumanRequest_

typedef ::rosplan_tiago_core_msgs::GetHumanRequest_<std::allocator<void> > GetHumanRequest;

typedef boost::shared_ptr< ::rosplan_tiago_core_msgs::GetHumanRequest > GetHumanRequestPtr;
typedef boost::shared_ptr< ::rosplan_tiago_core_msgs::GetHumanRequest const> GetHumanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator1> & lhs, const ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator2> & rhs)
{
  return lhs.human_name == rhs.human_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator1> & lhs, const ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_tiago_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae4eb3e5baf56fa3671c054486fa4784";
  }

  static const char* value(const ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae4eb3e5baf56fa3ULL;
  static const uint64_t static_value2 = 0x671c054486fa4784ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_tiago_core_msgs/GetHumanRequest";
  }

  static const char* value(const ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# service for getting person parameters\n"
"string human_name\n"
;
  }

  static const char* value(const ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.human_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHumanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_tiago_core_msgs::GetHumanRequest_<ContainerAllocator>& v)
  {
    s << indent << "human_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.human_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_TIAGO_CORE_MSGS_MESSAGE_GETHUMANREQUEST_H
