// Generated by gencpp from file rosplan_tiago_core_msgs/GetHumanResponse.msg
// DO NOT EDIT!


#ifndef ROSPLAN_TIAGO_CORE_MSGS_MESSAGE_GETHUMANRESPONSE_H
#define ROSPLAN_TIAGO_CORE_MSGS_MESSAGE_GETHUMANRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <people_msgs/Person.h>

namespace rosplan_tiago_core_msgs
{
template <class ContainerAllocator>
struct GetHumanResponse_
{
  typedef GetHumanResponse_<ContainerAllocator> Type;

  GetHumanResponse_()
    : human()  {
    }
  GetHumanResponse_(const ContainerAllocator& _alloc)
    : human(_alloc)  {
  (void)_alloc;
    }



   typedef  ::people_msgs::Person_<ContainerAllocator>  _human_type;
  _human_type human;





  typedef boost::shared_ptr< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetHumanResponse_

typedef ::rosplan_tiago_core_msgs::GetHumanResponse_<std::allocator<void> > GetHumanResponse;

typedef boost::shared_ptr< ::rosplan_tiago_core_msgs::GetHumanResponse > GetHumanResponsePtr;
typedef boost::shared_ptr< ::rosplan_tiago_core_msgs::GetHumanResponse const> GetHumanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator1> & lhs, const ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator2> & rhs)
{
  return lhs.human == rhs.human;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator1> & lhs, const ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_tiago_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abe471379b81e0341b94c19d1a0e7c0c";
  }

  static const char* value(const ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabe471379b81e034ULL;
  static const uint64_t static_value2 = 0x1b94c19d1a0e7c0cULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_tiago_core_msgs/GetHumanResponse";
  }

  static const char* value(const ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "people_msgs/Person human\n"
"\n"
"\n"
"================================================================================\n"
"MSG: people_msgs/Person\n"
"string              name\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Point velocity\n"
"float64             reliability\n"
"string[]            tagnames\n"
"string[]            tags\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.human);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHumanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_tiago_core_msgs::GetHumanResponse_<ContainerAllocator>& v)
  {
    s << indent << "human: ";
    s << std::endl;
    Printer< ::people_msgs::Person_<ContainerAllocator> >::stream(s, indent + "  ", v.human);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_TIAGO_CORE_MSGS_MESSAGE_GETHUMANRESPONSE_H
