(cl:defpackage repeat_action_server-msg
  (:use )
  (:export
   "<ASKTOREPEATACTION>"
   "ASKTOREPEATACTION"
   "<ASKTOREPEATACTIONFEEDBACK>"
   "ASKTOREPEATACTIONFEEDBACK"
   "<ASKTOREPEATACTIONGOAL>"
   "ASKTOREPEATACTIONGOAL"
   "<ASKTOREPEATACTIONRESULT>"
   "ASKTOREPEATACTIONRESULT"
   "<ASKTOREPEATFEEDBACK>"
   "ASKTOREPEATFEEDBACK"
   "<ASKTOREPEATGOAL>"
   "ASKTOREPEATGOAL"
   "<ASKTOREPEATRESULT>"
   "ASKTOREPEATRESULT"
  ))

