; Auto-generated. Do not edit!


(cl:in-package repeat_action_server-msg)


;//! \htmlinclude AskToRepeatResult.msg.html

(cl:defclass <AskToRepeatResult> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass AskToRepeatResult (<AskToRepeatResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AskToRepeatResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AskToRepeatResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name repeat_action_server-msg:<AskToRepeatResult> is deprecated: use repeat_action_server-msg:AskToRepeatResult instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <AskToRepeatResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader repeat_action_server-msg:status-val is deprecated.  Use repeat_action_server-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AskToRepeatResult>) ostream)
  "Serializes a message object of type '<AskToRepeatResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'status) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AskToRepeatResult>) istream)
  "Deserializes a message object of type '<AskToRepeatResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'status) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AskToRepeatResult>)))
  "Returns string type for a message object of type '<AskToRepeatResult>"
  "repeat_action_server/AskToRepeatResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AskToRepeatResult)))
  "Returns string type for a message object of type 'AskToRepeatResult"
  "repeat_action_server/AskToRepeatResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AskToRepeatResult>)))
  "Returns md5sum for a message object of type '<AskToRepeatResult>"
  "da740a2c07d1e6cb851fc1b477c8705a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AskToRepeatResult)))
  "Returns md5sum for a message object of type 'AskToRepeatResult"
  "da740a2c07d1e6cb851fc1b477c8705a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AskToRepeatResult>)))
  "Returns full string definition for message of type '<AskToRepeatResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/String status~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AskToRepeatResult)))
  "Returns full string definition for message of type 'AskToRepeatResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/String status~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AskToRepeatResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AskToRepeatResult>))
  "Converts a ROS message object to a list"
  (cl:list 'AskToRepeatResult
    (cl:cons ':status (status msg))
))
