// Auto-generated. Do not edit!

// (in-package repeat_action_server.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class AskToRepeatGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.frame_id = null;
    }
    else {
      if (initObj.hasOwnProperty('frame_id')) {
        this.frame_id = initObj.frame_id
      }
      else {
        this.frame_id = new std_msgs.msg.String();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type AskToRepeatGoal
    // Serialize message field [frame_id]
    bufferOffset = std_msgs.msg.String.serialize(obj.frame_id, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type AskToRepeatGoal
    let len;
    let data = new AskToRepeatGoal(null);
    // Deserialize message field [frame_id]
    data.frame_id = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.String.getMessageSize(object.frame_id);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'repeat_action_server/AskToRepeatGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c4d894dd5f0b96f98e7c7ff563058377';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    std_msgs/String frame_id
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new AskToRepeatGoal(null);
    if (msg.frame_id !== undefined) {
      resolved.frame_id = std_msgs.msg.String.Resolve(msg.frame_id)
    }
    else {
      resolved.frame_id = new std_msgs.msg.String()
    }

    return resolved;
    }
};

module.exports = AskToRepeatGoal;
