// Auto-generated. Do not edit!

// (in-package rosplan_tiago_scenarios_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GiveItemFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.time_left = null;
      this.is_item_detected = null;
    }
    else {
      if (initObj.hasOwnProperty('time_left')) {
        this.time_left = initObj.time_left
      }
      else {
        this.time_left = 0;
      }
      if (initObj.hasOwnProperty('is_item_detected')) {
        this.is_item_detected = initObj.is_item_detected
      }
      else {
        this.is_item_detected = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GiveItemFeedback
    // Serialize message field [time_left]
    bufferOffset = _serializer.int16(obj.time_left, buffer, bufferOffset);
    // Serialize message field [is_item_detected]
    bufferOffset = _serializer.bool(obj.is_item_detected, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GiveItemFeedback
    let len;
    let data = new GiveItemFeedback(null);
    // Deserialize message field [time_left]
    data.time_left = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [is_item_detected]
    data.is_item_detected = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 3;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rosplan_tiago_scenarios_msgs/GiveItemFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f9bbf0397c36b53dd120d617b82d90da';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Message
    int16 time_left
    bool is_item_detected
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GiveItemFeedback(null);
    if (msg.time_left !== undefined) {
      resolved.time_left = msg.time_left;
    }
    else {
      resolved.time_left = 0
    }

    if (msg.is_item_detected !== undefined) {
      resolved.is_item_detected = msg.is_item_detected;
    }
    else {
      resolved.is_item_detected = false
    }

    return resolved;
    }
};

module.exports = GiveItemFeedback;
