// Generated by gencpp from file tiago_msgs/Command.msg
// DO NOT EDIT!


#ifndef TIAGO_MSGS_MESSAGE_COMMAND_H
#define TIAGO_MSGS_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiago_msgs
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : query_text()
    , intent_name()
    , param_names()
    , param_values()
    , confidence(0.0)
    , response_text()  {
    }
  Command_(const ContainerAllocator& _alloc)
    : query_text(_alloc)
    , intent_name(_alloc)
    , param_names(_alloc)
    , param_values(_alloc)
    , confidence(0.0)
    , response_text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _query_text_type;
  _query_text_type query_text;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _intent_name_type;
  _intent_name_type intent_name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _param_names_type;
  _param_names_type param_names;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _param_values_type;
  _param_values_type param_values;

   typedef double _confidence_type;
  _confidence_type confidence;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_text_type;
  _response_text_type response_text;





  typedef boost::shared_ptr< ::tiago_msgs::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiago_msgs::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::tiago_msgs::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::tiago_msgs::Command > CommandPtr;
typedef boost::shared_ptr< ::tiago_msgs::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiago_msgs::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiago_msgs::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tiago_msgs::Command_<ContainerAllocator1> & lhs, const ::tiago_msgs::Command_<ContainerAllocator2> & rhs)
{
  return lhs.query_text == rhs.query_text &&
    lhs.intent_name == rhs.intent_name &&
    lhs.param_names == rhs.param_names &&
    lhs.param_values == rhs.param_values &&
    lhs.confidence == rhs.confidence &&
    lhs.response_text == rhs.response_text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tiago_msgs::Command_<ContainerAllocator1> & lhs, const ::tiago_msgs::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tiago_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tiago_msgs::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago_msgs::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_msgs::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_msgs::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_msgs::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_msgs::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiago_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06b6118f5d2264a7eba07a99a0199967";
  }

  static const char* value(const ::tiago_msgs::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06b6118f5d2264a7ULL;
  static const uint64_t static_value2 = 0xeba07a99a0199967ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiago_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiago_msgs/Command";
  }

  static const char* value(const ::tiago_msgs::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiago_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string query_text\n"
"string intent_name\n"
"string[] param_names\n"
"string[] param_values\n"
"float64 confidence\n"
"string response_text\n"
;
  }

  static const char* value(const ::tiago_msgs::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiago_msgs::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.query_text);
      stream.next(m.intent_name);
      stream.next(m.param_names);
      stream.next(m.param_values);
      stream.next(m.confidence);
      stream.next(m.response_text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiago_msgs::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiago_msgs::Command_<ContainerAllocator>& v)
  {
    s << indent << "query_text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.query_text);
    s << indent << "intent_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.intent_name);
    s << indent << "param_names[]" << std::endl;
    for (size_t i = 0; i < v.param_names.size(); ++i)
    {
      s << indent << "  param_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.param_names[i]);
    }
    s << indent << "param_values[]" << std::endl;
    for (size_t i = 0; i < v.param_values.size(); ++i)
    {
      s << indent << "  param_values[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.param_values[i]);
    }
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "response_text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response_text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIAGO_MSGS_MESSAGE_COMMAND_H
