// Generated by gencpp from file tiago_msgs/DictionaryQuery.msg
// DO NOT EDIT!


#ifndef TIAGO_MSGS_MESSAGE_DICTIONARYQUERY_H
#define TIAGO_MSGS_MESSAGE_DICTIONARYQUERY_H

#include <ros/service_traits.h>


#include <tiago_msgs/DictionaryQueryRequest.h>
#include <tiago_msgs/DictionaryQueryResponse.h>


namespace tiago_msgs
{

struct DictionaryQuery
{

typedef DictionaryQueryRequest Request;
typedef DictionaryQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DictionaryQuery
} // namespace tiago_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tiago_msgs::DictionaryQuery > {
  static const char* value()
  {
    return "dd39d5a226cedb69f781a67374f10bd2";
  }

  static const char* value(const ::tiago_msgs::DictionaryQuery&) { return value(); }
};

template<>
struct DataType< ::tiago_msgs::DictionaryQuery > {
  static const char* value()
  {
    return "tiago_msgs/DictionaryQuery";
  }

  static const char* value(const ::tiago_msgs::DictionaryQuery&) { return value(); }
};


// service_traits::MD5Sum< ::tiago_msgs::DictionaryQueryRequest> should match
// service_traits::MD5Sum< ::tiago_msgs::DictionaryQuery >
template<>
struct MD5Sum< ::tiago_msgs::DictionaryQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_msgs::DictionaryQuery >::value();
  }
  static const char* value(const ::tiago_msgs::DictionaryQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_msgs::DictionaryQueryRequest> should match
// service_traits::DataType< ::tiago_msgs::DictionaryQuery >
template<>
struct DataType< ::tiago_msgs::DictionaryQueryRequest>
{
  static const char* value()
  {
    return DataType< ::tiago_msgs::DictionaryQuery >::value();
  }
  static const char* value(const ::tiago_msgs::DictionaryQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tiago_msgs::DictionaryQueryResponse> should match
// service_traits::MD5Sum< ::tiago_msgs::DictionaryQuery >
template<>
struct MD5Sum< ::tiago_msgs::DictionaryQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_msgs::DictionaryQuery >::value();
  }
  static const char* value(const ::tiago_msgs::DictionaryQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_msgs::DictionaryQueryResponse> should match
// service_traits::DataType< ::tiago_msgs::DictionaryQuery >
template<>
struct DataType< ::tiago_msgs::DictionaryQueryResponse>
{
  static const char* value()
  {
    return DataType< ::tiago_msgs::DictionaryQuery >::value();
  }
  static const char* value(const ::tiago_msgs::DictionaryQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIAGO_MSGS_MESSAGE_DICTIONARYQUERY_H
