// Generated by gencpp from file tiago_msgs/DictionaryQueryRequest.msg
// DO NOT EDIT!


#ifndef TIAGO_MSGS_MESSAGE_DICTIONARYQUERYREQUEST_H
#define TIAGO_MSGS_MESSAGE_DICTIONARYQUERYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiago_msgs
{
template <class ContainerAllocator>
struct DictionaryQueryRequest_
{
  typedef DictionaryQueryRequest_<ContainerAllocator> Type;

  DictionaryQueryRequest_()
    : word()  {
    }
  DictionaryQueryRequest_(const ContainerAllocator& _alloc)
    : word(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _word_type;
  _word_type word;





  typedef boost::shared_ptr< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DictionaryQueryRequest_

typedef ::tiago_msgs::DictionaryQueryRequest_<std::allocator<void> > DictionaryQueryRequest;

typedef boost::shared_ptr< ::tiago_msgs::DictionaryQueryRequest > DictionaryQueryRequestPtr;
typedef boost::shared_ptr< ::tiago_msgs::DictionaryQueryRequest const> DictionaryQueryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator1> & lhs, const ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.word == rhs.word;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator1> & lhs, const ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tiago_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf5cbdd7f0c6b9eaa898f882ab6eade6";
  }

  static const char* value(const ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf5cbdd7f0c6b9eaULL;
  static const uint64_t static_value2 = 0xa898f882ab6eade6ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiago_msgs/DictionaryQueryRequest";
  }

  static const char* value(const ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string word\n"
;
  }

  static const char* value(const ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.word);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DictionaryQueryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiago_msgs::DictionaryQueryRequest_<ContainerAllocator>& v)
  {
    s << indent << "word: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.word);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIAGO_MSGS_MESSAGE_DICTIONARYQUERYREQUEST_H
